package com.construct.messenger.transport

import com.construct.messenger.transport.TransportRoute.Effect
import com.construct.messenger.transport.TransportRoute.Event
import com.construct.messenger.transport.TransportRoute.Mode
import com.construct.messenger.transport.TransportRoute.RpcFailure
import com.construct.messenger.transport.TransportRoute.State
import com.construct.messenger.transport.TransportRoute.StreamFailure
import com.construct.messenger.transport.TransportRoute.StreamMethod
import com.construct.messenger.transport.TransportRoute.Target
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * [TransportRoute] against construct-protos `conformance/transport_route.json`, vendored into
 * `src/test/resources/conformance/`. iOS runs the same file against `TransportReducer`. The file is
 * generated by `check_transport_route.py`; re-copy it when it changes.
 */
class TransportRouteVectorsTest {

    private val doc: JSONObject = JSONObject(
        javaClass.classLoader!!.getResourceAsStream("conformance/transport_route.json")!!.bufferedReader().readText(),
    )
    private val now = doc.getLong("now_ms")
    private val veil = doc.getJSONObject("veil_target").let { Target.Veil(it.getInt("port"), it.getString("relay")) }

    @Test
    fun `every case ends where the vectors say`() {
        val cases = doc.getJSONArray("cases")
        assertTrue("vectors present", cases.length() > 40)
        for (i in 0 until cases.length()) {
            val c = cases.getJSONObject(i)
            val name = c.getString("name")
            if (c.has("initial")) {
                val init = c.getJSONObject("initial")
                val state = TransportRoute.initial(mode(init.getString("mode")), init.getBoolean("censored"), init.getBoolean("reachable"))
                assertEquals(name, state(c.getJSONObject("expect_state")), state)
                continue
            }
            val mode = mode(c.getString("mode"))
            val config = config(c.optJSONObject("config"))
            var state = state(c.getJSONObject("state"))
            var effects = emptyList<Effect>()
            val events = c.getJSONArray("events")
            for (j in 0 until events.length()) {
                val outcome = TransportRoute.reduce(state, event(events.getJSONObject(j)), mode, config, now)
                state = outcome.state
                effects = outcome.effects
            }
            assertEquals("$name: state", state(c.getJSONObject("expect_state")), state)
            assertEquals("$name: effects", effects(c.getJSONArray("expect_effects")), effects)
        }
    }

    @Test
    fun `the default config is the vectors' default`() {
        val d = doc.getJSONObject("default_config")
        assertEquals(config(d), TransportRoute.Config())
    }

    private fun mode(s: String) = Mode.valueOf(s.uppercase())

    private fun config(o: JSONObject?): TransportRoute.Config {
        val base = TransportRoute.Config()
        if (o == null) return base
        return base.copy(
            directFailThreshold = o.optInt("direct_fail_threshold", base.directFailThreshold),
            midSessionDeathWeight = o.optInt("mid_session_death_weight", base.midSessionDeathWeight),
            allowDirectToVeilEscalation = o.optBoolean("allow_direct_to_veil_escalation", base.allowDirectToVeilEscalation),
            veilCooldownMs = o.optLong("veil_cooldown_ms", base.veilCooldownMs),
        )
    }

    private fun target(s: String) = if (s == "veil") veil else Target.Direct

    private fun state(o: JSONObject): State = when (o.getString("kind")) {
        "offline" -> State.Offline
        "direct" -> State.Direct(o.getInt("fails"))
        "veil_probing" -> State.VeilProbing
        "veil_active" -> State.VeilActive(o.getString("relay"), o.getInt("port"), o.getLong("since_ms"))
        "veil_cooldown" -> State.VeilCooldown(o.getLong("until_ms"))
        else -> error("unknown state ${o.getString("kind")}")
    }

    private fun event(o: JSONObject): Event = when (o.getString("kind")) {
        "rpc_succeeded" -> Event.RpcSucceeded(target(o.getString("via")), o.getInt("latency_ms"))
        "rpc_failed" -> Event.RpcFailed(RpcFailure.valueOf(o.getString("failure").uppercase()), target(o.getString("via")), o.getBoolean("foreground"))
        "stream_opened" -> Event.StreamOpened(StreamMethod.valueOf(o.getString("method").uppercase()), target(o.getString("via")))
        "stream_failed" -> Event.StreamFailed(
            StreamMethod.valueOf(o.getString("method").uppercase()),
            StreamFailure.valueOf(o.getString("failure").uppercase()),
            target(o.getString("via")),
        )
        "network_path_changed" -> Event.NetworkPathChanged(o.getBoolean("reachable"), o.getBoolean("censored"))
        "veil_mode_changed" -> Event.VeilModeChanged(o.getBoolean("censored"))
        "veil_config_changed" -> Event.VeilConfigChanged
        "background_wake" -> Event.BackgroundWake
        "proxy_started" -> Event.ProxyStarted(o.getString("relay"), o.getInt("port"), o.getBoolean("restarted"))
        "proxy_start_failed" -> Event.ProxyStartFailed(if (o.isNull("relay")) null else o.getString("relay"), o.getString("reason"))
        "cooldown_elapsed" -> Event.CooldownElapsed
        "manual_reset" -> Event.ManualReset
        else -> error("unknown event ${o.getString("kind")}")
    }

    private fun effects(a: JSONArray): List<Effect> = (0 until a.length()).map { i ->
        val o = a.getJSONObject(i)
        when (o.getString("kind")) {
            "invalidate_grpc_client" -> Effect.InvalidateGrpcClient
            "set_veil_port" -> Effect.SetVeilPort(if (o.isNull("port")) null else o.getInt("port"))
            "request_proxy_start" -> Effect.RequestProxyStart
            "request_proxy_stop" -> Effect.RequestProxyStop
            "schedule_cooldown_end" -> Effect.ScheduleCooldownEnd(o.getLong("at_ms"))
            else -> error("unknown effect ${o.getString("kind")}")
        }
    }
}
